version: "3"
#
# usage:
# sudo docker-compose build
# sudo docker-compose up

services: 
    mongo:
        image: mongo:latest
        container_name: 'mongo'
        ports:
            - "27017:27017"
        volumes:
            - data:/data/db 

    frontend:
        build: ./angular-app
        ports:
            - "80:80"
        links:
            - 'backend'

    backend:
        build: ./express-server
        ports:
            - "8001:8001"
        depends_on: 
            - mongo
volumes: 
    data:
